chore(devpod): commandが存在するときはinstallしない

diff --git a/run_once_after_03_darwin-settings.sh.tmpl b/run_once_after_03_darwin-settings.sh.tmpl
--- a/run_once_after_03_darwin-settings.sh.tmpl
+++ b/run_once_after_03_darwin-settings.sh.tmpl
@@ -47,8 +47,12 @@ if ! command -v rustup > /dev/null; then
 fi
 # devpod CLI
 # https://devpod.sh/docs/getting-started/install#optional-install-devpod-cli
-DEVPOD_DIR=$HOME/.local/share/devpod
-mkdir -p $DEVPOD_DIR
-DEVPOD_HOME=$DEVPOD_DIR curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-darwin-arm64" && sudo install -c -m 0755 devpod $HOME/.local/bin/ && rm -f devpod
+
+if ! command -v devpod > /dev/null; then
+    echo "devpod not found. installing..."
+    DEVPOD_DIR=$HOME/.local/share/devpod
+    mkdir -p $DEVPOD_DIR
+    DEVPOD_HOME=$DEVPOD_DIR curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-darwin-arm64" && sudo install -c -m 0755 devpod $HOME/.local/bin/ && rm -f devpod
+fi
 
 {{ end -}}
